import React from 'react';
import { Page, Text, View, Document, StyleSheet, PDFViewer, Image } from '@react-pdf/renderer';
import * as API from '../../Api';
import {Table, TableCell, TableHeader, TableBody, DataTableCell} from '@david.kucsai/react-pdf-table'


const debug = false

// Create styles
const styles = StyleSheet.create({
    page: {

        width: 600,
        padding: '1cm'
    },
    section: {
        margin: 10,
        padding: 10,
        flexGrow: 1
    },
    table: { 
        tableView: {marginTop: '70px'},
        tableHead: {fontSize: 5}
    }

});


let employees = [
    {
        "id": 1,
        "name": "AGATHOS, SPIROS",
        "phone": "0414964220",
        "dob": "2000-09-10",
        "job_code": "594",
        "location": "A",
        "inactive": 1,
        "anniversary_dt": "2019-02-05",
        "company": "M",
        "bonus": 0,
        "bonus_type": null,
        "car_allowance": 0,
        "apprentice_year": "3",
        "rdo_bal": "111.75",
        "pld": "208.00",
        "anl": "177.24",
        "sick_bal": "126.68",
        "rollover": 0,
        "last_timesheet": 9629
    },
    {
        "id": 2,
        "name": "AILAO, ROBERT",
        "phone": "0411985882",
        "dob": "1985-10-13",
        "job_code": "594",
        "location": "P",
        "inactive": 1,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 100,
        "bonus_type": "L",
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "8.00",
        "pld": "9.00",
        "anl": "24.77",
        "sick_bal": "612.13",
        "rollover": 0,
        "last_timesheet": 9614
    },
    {
        "id": 3,
        "name": "ALAVANOS, CHRIS",
        "phone": "0424097044",
        "dob": "1994-08-08",
        "job_code": "sick",
        "location": "P",
        "inactive": 1,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 0,
        "bonus_type": "",
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "0.00",
        "pld": "0.00",
        "anl": "0.00",
        "sick_bal": "62.71",
        "rollover": 0,
        "last_timesheet": null
    },
    {
        "id": 4,
        "name": "ALEVRAS, ILIAS",
        "phone": "0401731110",
        "dob": "1984-02-12",
        "job_code": "594",
        "location": "P",
        "inactive": 1,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 0,
        "bonus_type": null,
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "8.00",
        "pld": "19.00",
        "anl": "30.77",
        "sick_bal": "15.37",
        "rollover": 0,
        "last_timesheet": 9631
    },
    {
        "id": 6,
        "name": "AUSTIN, JONATHAN",
        "phone": "0401661679",
        "dob": "1989-01-09",
        "job_code": "608",
        "location": "P",
        "inactive": 1,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 100,
        "bonus_type": "L",
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "11.00",
        "pld": "6.00",
        "anl": "39.95",
        "sick_bal": "46.62",
        "rollover": 0,
        "last_timesheet": 9644
    },
    {
        "id": 7,
        "name": "BAILEY, MARCUS",
        "phone": "0422270487",
        "dob": "1989-08-08",
        "job_code": "001",
        "location": "A",
        "inactive": 1,
        "anniversary_dt": "2018-10-28",
        "company": "C",
        "bonus": 0,
        "bonus_type": null,
        "car_allowance": 0,
        "apprentice_year": "3",
        "rdo_bal": "4.00",
        "pld": "33.00",
        "anl": "204.32",
        "sick_bal": "158.10",
        "rollover": 0,
        "last_timesheet": null
    },
    {
        "id": 8,
        "name": "BAKER, MICHAEL",
        "phone": "0418144098",
        "dob": "1959-12-01",
        "job_code": "001",
        "location": "O",
        "inactive": 1,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 0,
        "bonus_type": null,
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "12.00",
        "pld": "43.50",
        "anl": "551.94",
        "sick_bal": "333.73",
        "rollover": 0,
        "last_timesheet": 9600
    },
    {
        "id": 9,
        "name": "BAZOUNI, JOHN",
        "phone": "0410468622",
        "dob": "1985-08-15",
        "job_code": "001",
        "location": "P",
        "inactive": 1,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 0,
        "bonus_type": null,
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "24.00",
        "pld": "24.00",
        "anl": "105.89",
        "sick_bal": "69.43",
        "rollover": 0,
        "last_timesheet": null
    },
    {
        "id": 10,
        "name": "BEZERRA DOS SANTOS, CARLOS IRAN",
        "phone": "0431532056",
        "dob": "1986-11-30",
        "job_code": "594",
        "location": "L",
        "inactive": 1,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 0,
        "bonus_type": null,
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "0.00",
        "pld": "0.00",
        "anl": "0.00",
        "sick_bal": "0.00",
        "rollover": 0,
        "last_timesheet": 9623
    },
    {
        "id": 11,
        "name": "BIRNIE, JAYDEN",
        "phone": "0450510067",
        "dob": "2002-02-05",
        "job_code": "594",
        "location": "A",
        "inactive": 1,
        "anniversary_dt": "2019-06-24",
        "company": "C",
        "bonus": 0,
        "bonus_type": null,
        "car_allowance": 0,
        "apprentice_year": "3",
        "rdo_bal": "10.00",
        "pld": "11.25",
        "anl": "108.32",
        "sick_bal": "154.40",
        "rollover": 0,
        "last_timesheet": 9628
    },
    {
        "id": 12,
        "name": "BORG, CHRISTOPHER",
        "phone": "0404001084",
        "dob": "1983-08-31",
        "job_code": "anl",
        "location": "P",
        "inactive": 1,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 200,
        "bonus_type": "F",
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "130.00",
        "pld": "38.50",
        "anl": "55.12",
        "sick_bal": "51.30",
        "rollover": 0,
        "last_timesheet": 9637
    },
    {
        "id": 13,
        "name": "BOYD, GLENN",
        "phone": "0412013543",
        "dob": "1973-04-27",
        "job_code": "609",
        "location": "P",
        "inactive": 1,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 100,
        "bonus_type": "L",
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "49.00",
        "pld": "40.00",
        "anl": "90.48",
        "sick_bal": "170.16",
        "rollover": 0,
        "last_timesheet": 9602
    },
    {
        "id": 14,
        "name": "BROADRIBB, JUSTIN",
        "phone": "0425721996",
        "dob": "1996-05-10",
        "job_code": "608",
        "location": "P",
        "inactive": 1,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 0,
        "bonus_type": null,
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "96.00",
        "pld": "22.25",
        "anl": "182.17",
        "sick_bal": "282.77",
        "rollover": 0,
        "last_timesheet": 9639
    },
    {
        "id": 15,
        "name": "BYRNE, BARRY",
        "phone": "0449673031",
        "dob": "1982-04-15",
        "job_code": "604",
        "location": "P",
        "inactive": 1,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 0,
        "bonus_type": null,
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "14.00",
        "pld": "186.25",
        "anl": "59.10",
        "sick_bal": "357.92",
        "rollover": 0,
        "last_timesheet": 9588
    },
    {
        "id": 16,
        "name": "CARDWELL, MILO",
        "phone": "0413420018",
        "dob": "2000-02-06",
        "job_code": "608",
        "location": "A",
        "inactive": 1,
        "anniversary_dt": "2018-10-15",
        "company": "C",
        "bonus": 0,
        "bonus_type": null,
        "car_allowance": 0,
        "apprentice_year": "3",
        "rdo_bal": "-0.25",
        "pld": "0.00",
        "anl": "-0.03",
        "sick_bal": "70.94",
        "rollover": 0,
        "last_timesheet": null
    },
    {
        "id": 17,
        "name": "CARMO DE SOUZA MACIEL, EDSON",
        "phone": null,
        "dob": "1977-02-11",
        "job_code": "551",
        "location": "L",
        "inactive": 1,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 0,
        "bonus_type": null,
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "0.00",
        "pld": "0.00",
        "anl": "0.00",
        "sick_bal": "0.00",
        "rollover": 0,
        "last_timesheet": null
    },
    {
        "id": 18,
        "name": "CHAPMAN, DANNY",
        "phone": "0412281543",
        "dob": "1995-07-02",
        "job_code": "594",
        "location": "L",
        "inactive": 1,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 0,
        "bonus_type": null,
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "2.00",
        "pld": "57.00",
        "anl": "35.62",
        "sick_bal": "144.85",
        "rollover": 0,
        "last_timesheet": 9618
    },
    {
        "id": 19,
        "name": "COLE, EDEN",
        "phone": "0408009536",
        "dob": "1968-09-18",
        "job_code": null,
        "location": "P",
        "inactive": 1,
        "anniversary_dt": null,
        "company": "M",
        "bonus": 200,
        "bonus_type": "F",
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "21.00",
        "pld": "9.00",
        "anl": "99.09",
        "sick_bal": "84.38",
        "rollover": 0,
        "last_timesheet": null
    },
    {
        "id": 20,
        "name": "COONEY, JOE",
        "phone": "0405106265",
        "dob": "1989-11-23",
        "job_code": "001",
        "location": "P",
        "inactive": 1,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 0,
        "bonus_type": null,
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "8.00",
        "pld": "10.00",
        "anl": "10.76",
        "sick_bal": "307.44",
        "rollover": 0,
        "last_timesheet": 9650
    },
    {
        "id": 21,
        "name": "Cudd, Robert",
        "phone": null,
        "dob": "1976-07-06",
        "job_code": "594",
        "location": "P",
        "inactive": 0,
        "anniversary_dt": null,
        "company": "C",
        "bonus": null,
        "bonus_type": "F",
        "car_allowance": null,
        "apprentice_year": null,
        "rdo_bal": null,
        "pld": null,
        "anl": null,
        "sick_bal": "660.49",
        "rollover": 0,
        "last_timesheet": 9613
    },
    {
        "id": 22,
        "name": "CUPAC, DRAGAN",
        "phone": "0431523355",
        "dob": "1992-05-20",
        "job_code": "608",
        "location": "P",
        "inactive": 0,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 200,
        "bonus_type": "F",
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "11.80",
        "pld": "16.80",
        "anl": "97.95",
        "sick_bal": "311.57",
        "rollover": 0,
        "last_timesheet": 9643
    },
    {
        "id": 23,
        "name": "CURRAN, DANIEL",
        "phone": "0434552995",
        "dob": "1974-04-18",
        "job_code": "608",
        "location": "P",
        "inactive": 0,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 0,
        "bonus_type": null,
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "4.00",
        "pld": "4.00",
        "anl": "6.16",
        "sick_bal": "3.14",
        "rollover": 0,
        "last_timesheet": 9607
    },
    {
        "id": 24,
        "name": "CURRIE, MARCUS",
        "phone": "0404244179",
        "dob": "1977-11-01",
        "job_code": "594",
        "location": "P",
        "inactive": 0,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 0,
        "bonus_type": "",
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "38.50",
        "pld": "21.00",
        "anl": "90.79",
        "sick_bal": "231.24",
        "rollover": 0,
        "last_timesheet": 9630
    },
    {
        "id": 25,
        "name": "DAVISON, IAN",
        "phone": "0420492232",
        "dob": "1985-05-01",
        "job_code": "607",
        "location": "P",
        "inactive": 0,
        "anniversary_dt": null,
        "company": "M",
        "bonus": 0,
        "bonus_type": null,
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "12.00",
        "pld": "16.75",
        "anl": "6.88",
        "sick_bal": "107.06",
        "rollover": 0,
        "last_timesheet": 9594
    },
    {
        "id": 26,
        "name": "ECHENIQUE, MARIA",
        "phone": "0404935990",
        "dob": "1993-05-10",
        "job_code": null,
        "location": "L",
        "inactive": 1,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 0,
        "bonus_type": "",
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "4.00",
        "pld": "6.00",
        "anl": "11.97",
        "sick_bal": "0.00",
        "rollover": 0,
        "last_timesheet": null
    },
    {
        "id": 27,
        "name": "EL- HUSSEIN, KHALID",
        "phone": "0410870114",
        "dob": "1990-08-19",
        "job_code": "594",
        "location": "P",
        "inactive": 0,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 100,
        "bonus_type": "L",
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "30.00",
        "pld": "26.00",
        "anl": "375.52",
        "sick_bal": "211.62",
        "rollover": 0,
        "last_timesheet": 9611
    },
    {
        "id": 28,
        "name": "FAALUA, MOSES",
        "phone": "0457470627",
        "dob": "1998-10-23",
        "job_code": "604",
        "location": "A",
        "inactive": 0,
        "anniversary_dt": "2019-07-24",
        "company": "C",
        "bonus": 0,
        "bonus_type": null,
        "car_allowance": 0,
        "apprentice_year": "3",
        "rdo_bal": "5.00",
        "pld": "18.25",
        "anl": "36.90",
        "sick_bal": "203.31",
        "rollover": 0,
        "last_timesheet": 9590
    },
    {
        "id": 29,
        "name": "FERREIRA BEZERRA, FELIPE",
        "phone": "0403364997",
        "dob": "1986-03-26",
        "job_code": null,
        "location": "L",
        "inactive": 1,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 0,
        "bonus_type": "",
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "0.00",
        "pld": "0.00",
        "anl": "0.00",
        "sick_bal": "0.00",
        "rollover": 0,
        "last_timesheet": null
    },
    {
        "id": 30,
        "name": "FLETCHER, NATHAN",
        "phone": "0438219703",
        "dob": "1976-12-22",
        "job_code": "500",
        "location": "P",
        "inactive": 1,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 0,
        "bonus_type": null,
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "38.00",
        "pld": "42.00",
        "anl": "66.47",
        "sick_bal": "105.19",
        "rollover": 0,
        "last_timesheet": null
    },
    {
        "id": 31,
        "name": "FLETCHER, NICK",
        "phone": "0439391141",
        "dob": "1976-07-09",
        "job_code": "604",
        "location": "P",
        "inactive": 0,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 200,
        "bonus_type": "F",
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "67.00",
        "pld": "36.00",
        "anl": "134.65",
        "sick_bal": "324.09",
        "rollover": 0,
        "last_timesheet": 9591
    },
    {
        "id": 32,
        "name": "FLETCHER, SEBASTIAN",
        "phone": "0427053777",
        "dob": "1999-12-31",
        "job_code": "582",
        "location": "A",
        "inactive": 1,
        "anniversary_dt": "2018-11-14",
        "company": "C",
        "bonus": 0,
        "bonus_type": null,
        "car_allowance": 0,
        "apprentice_year": "2",
        "rdo_bal": "16.00",
        "pld": "66.00",
        "anl": "169.19",
        "sick_bal": "112.65",
        "rollover": 0,
        "last_timesheet": null
    },
    {
        "id": 33,
        "name": "FRISKEN, ALEX",
        "phone": "0417276761",
        "dob": "1992-11-13",
        "job_code": "001",
        "location": "O",
        "inactive": 0,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 0,
        "bonus_type": null,
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "0.00",
        "pld": "0.00",
        "anl": "0.00",
        "sick_bal": "0.00",
        "rollover": 0,
        "last_timesheet": 9638
    },
    {
        "id": 34,
        "name": "GAUCI, JOSEPH",
        "phone": "0416155087",
        "dob": "2000-11-05",
        "job_code": "525",
        "location": "A",
        "inactive": 1,
        "anniversary_dt": "2018-10-23",
        "company": "C",
        "bonus": 0,
        "bonus_type": null,
        "car_allowance": 0,
        "apprentice_year": "3",
        "rdo_bal": "10.00",
        "pld": "12.00",
        "anl": "107.08",
        "sick_bal": "77.50",
        "rollover": 0,
        "last_timesheet": null
    },
    {
        "id": 35,
        "name": "GAZAL, DANIEL",
        "phone": "0431288032",
        "dob": "1997-10-02",
        "job_code": "582",
        "location": "A",
        "inactive": 1,
        "anniversary_dt": "2018-09-03",
        "company": "C",
        "bonus": 0,
        "bonus_type": null,
        "car_allowance": 0,
        "apprentice_year": "4",
        "rdo_bal": "10.00",
        "pld": "30.00",
        "anl": "17.25",
        "sick_bal": "57.83",
        "rollover": 0,
        "last_timesheet": null
    },
    {
        "id": 36,
        "name": "GLEESON, DANIEL",
        "phone": "0449214541",
        "dob": "1983-02-09",
        "job_code": "579",
        "location": "P",
        "inactive": 1,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 0,
        "bonus_type": null,
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "31.25",
        "pld": "39.00",
        "anl": "45.68",
        "sick_bal": "115.04",
        "rollover": 0,
        "last_timesheet": null
    },
    {
        "id": 37,
        "name": "GUERREIRO, MASEN",
        "phone": "0456579510",
        "dob": "2000-04-28",
        "job_code": "551",
        "location": "A",
        "inactive": 1,
        "anniversary_dt": "2019-01-31",
        "company": "C",
        "bonus": 0,
        "bonus_type": null,
        "car_allowance": 0,
        "apprentice_year": "2",
        "rdo_bal": "16.00",
        "pld": "28.00",
        "anl": "63.04",
        "sick_bal": "31.56",
        "rollover": 0,
        "last_timesheet": null
    },
    {
        "id": 38,
        "name": "HAEBICH, LUKE",
        "phone": "0450984515",
        "dob": "1985-01-29",
        "job_code": "594",
        "location": "P",
        "inactive": 1,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 0,
        "bonus_type": null,
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "102.00",
        "pld": "130.00",
        "anl": "190.78",
        "sick_bal": "115.35",
        "rollover": 0,
        "last_timesheet": null
    },
    {
        "id": 39,
        "name": "HALLIDAY, ANTHONY",
        "phone": "0466667500",
        "dob": "1976-11-13",
        "job_code": "594",
        "location": "O",
        "inactive": 0,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 200,
        "bonus_type": "F",
        "car_allowance": 170,
        "apprentice_year": null,
        "rdo_bal": "30.00",
        "pld": "32.00",
        "anl": "107.89",
        "sick_bal": "643.29",
        "rollover": 0,
        "last_timesheet": 9603
    },
    {
        "id": 40,
        "name": "HASSANPOUR, MOHAMMAD",
        "phone": "0450000803",
        "dob": "1994-07-11",
        "job_code": "594",
        "location": "P",
        "inactive": 0,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 0,
        "bonus_type": "",
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "4.00",
        "pld": "48.00",
        "anl": "38.16",
        "sick_bal": "43.06",
        "rollover": 0,
        "last_timesheet": 9625
    },
    {
        "id": 42,
        "name": "JOHNSON, ADAM",
        "phone": "0466667722",
        "dob": "1967-11-03",
        "job_code": "594",
        "location": "P",
        "inactive": 0,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 300,
        "bonus_type": "F",
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "93.00",
        "pld": "284.00",
        "anl": "340.85",
        "sick_bal": "724.83",
        "rollover": 0,
        "last_timesheet": 9581
    },
    {
        "id": 43,
        "name": "JORDAN, SHAUN",
        "phone": "0411162939",
        "dob": "1997-01-09",
        "job_code": "579",
        "location": "P",
        "inactive": 0,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 0,
        "bonus_type": null,
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "4.00",
        "pld": "4.00",
        "anl": "5.77",
        "sick_bal": "11.38",
        "rollover": 0,
        "last_timesheet": 9648
    },
    {
        "id": 44,
        "name": "KALACHE, JASON",
        "phone": "0450018122",
        "dob": "1987-05-25",
        "job_code": "551",
        "location": "P",
        "inactive": 1,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 0,
        "bonus_type": null,
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "0.00",
        "pld": "0.00",
        "anl": "0.00",
        "sick_bal": "23.07",
        "rollover": 0,
        "last_timesheet": null
    },
    {
        "id": 45,
        "name": "KARAVELATZIS, ANDREW",
        "phone": "0432335800",
        "dob": "1988-06-01",
        "job_code": "002",
        "location": "A",
        "inactive": 0,
        "anniversary_dt": "2018-06-08",
        "company": "M",
        "bonus": 0,
        "bonus_type": null,
        "car_allowance": 0,
        "apprentice_year": "4",
        "rdo_bal": "10.75",
        "pld": "10.50",
        "anl": "6.75",
        "sick_bal": "201.58",
        "rollover": 0,
        "last_timesheet": 9608
    },
    {
        "id": 46,
        "name": "KARAVELATZIS, DANIEL",
        "phone": "0422106933",
        "dob": "1987-05-23",
        "job_code": "anl",
        "location": "P",
        "inactive": 0,
        "anniversary_dt": null,
        "company": "M",
        "bonus": 200,
        "bonus_type": "F",
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "10.25",
        "pld": "10.00",
        "anl": "74.84",
        "sick_bal": "458.17",
        "rollover": 0,
        "last_timesheet": 9609
    },
    {
        "id": 47,
        "name": "KOVACIC, STOJAN",
        "phone": "0405533438",
        "dob": "1981-05-10",
        "job_code": "608",
        "location": "P",
        "inactive": 0,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 100,
        "bonus_type": "L",
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "57.00",
        "pld": "60.25",
        "anl": "77.09",
        "sick_bal": "698.20",
        "rollover": 0,
        "last_timesheet": 9610
    },
    {
        "id": 48,
        "name": "KRIMIZIS, MIRIANA",
        "phone": "0421092092",
        "dob": "1975-10-01",
        "job_code": "001",
        "location": "O",
        "inactive": 0,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 0,
        "bonus_type": null,
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "0.00",
        "pld": "0.00",
        "anl": "0.00",
        "sick_bal": "0.00",
        "rollover": 0,
        "last_timesheet": 9579
    },
    {
        "id": 49,
        "name": "MATAR, KALED",
        "phone": "0450347708",
        "dob": "1998-07-17",
        "job_code": "604",
        "location": "P",
        "inactive": 0,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 0,
        "bonus_type": "",
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "78.00",
        "pld": "53.75",
        "anl": "59.05",
        "sick_bal": "157.49",
        "rollover": 0,
        "last_timesheet": 9640
    },
    {
        "id": 50,
        "name": "MATAR, OMAR",
        "phone": "0424675452",
        "dob": "1999-10-08",
        "job_code": "604",
        "location": "P",
        "inactive": 0,
        "anniversary_dt": "2018-11-13",
        "company": "C",
        "bonus": 0,
        "bonus_type": null,
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "152.00",
        "pld": "109.75",
        "anl": "148.79",
        "sick_bal": "157.76",
        "rollover": 0,
        "last_timesheet": 9641
    },
    {
        "id": 51,
        "name": "MATTA, CHARBEL",
        "phone": "0404786607",
        "dob": "1990-03-30",
        "job_code": "609",
        "location": "P",
        "inactive": 0,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 200,
        "bonus_type": "F",
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "38.00",
        "pld": "39.00",
        "anl": "96.64",
        "sick_bal": "150.58",
        "rollover": 0,
        "last_timesheet": 9598
    },
    {
        "id": 52,
        "name": "MEYN, MARK",
        "phone": "0418631730",
        "dob": "1964-09-03",
        "job_code": "551",
        "location": "P",
        "inactive": 1,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 0,
        "bonus_type": null,
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "28.00",
        "pld": "41.50",
        "anl": "104.00",
        "sick_bal": "51.98",
        "rollover": 0,
        "last_timesheet": null
    },
    {
        "id": 53,
        "name": "MOLLUSO, MARIE",
        "phone": "0404061551",
        "dob": "1980-05-02",
        "job_code": "001",
        "location": "O",
        "inactive": 0,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 0,
        "bonus_type": null,
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "0.00",
        "pld": "0.00",
        "anl": "394.63",
        "sick_bal": "214.68",
        "rollover": 0,
        "last_timesheet": 9578
    },
    {
        "id": 54,
        "name": "MOSER, ROBERT",
        "phone": "0414886970",
        "dob": "1956-01-28",
        "job_code": "594",
        "location": "P",
        "inactive": 0,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 0,
        "bonus_type": "",
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "23.00",
        "pld": "7.01",
        "anl": "9.40",
        "sick_bal": "284.20",
        "rollover": 0,
        "last_timesheet": 9627
    },
    {
        "id": 56,
        "name": "MURANS, DEAN",
        "phone": "0410652265",
        "dob": "1975-06-30",
        "job_code": "525",
        "location": "P",
        "inactive": 1,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 0,
        "bonus_type": null,
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "14.00",
        "pld": "30.50",
        "anl": "22.78",
        "sick_bal": "43.35",
        "rollover": 0,
        "last_timesheet": null
    },
    {
        "id": 57,
        "name": "MUSSO, THOMAS",
        "phone": "0468304991",
        "dob": "1996-08-09",
        "job_code": "577",
        "location": "A",
        "inactive": 1,
        "anniversary_dt": "2019-02-19",
        "company": "M",
        "bonus": 0,
        "bonus_type": null,
        "car_allowance": 0,
        "apprentice_year": "2",
        "rdo_bal": "14.00",
        "pld": "12.00",
        "anl": "47.39",
        "sick_bal": "23.68",
        "rollover": 0,
        "last_timesheet": null
    },
    {
        "id": 58,
        "name": "O'NEILL, NATHAN",
        "phone": "0434614760",
        "dob": "1988-06-16",
        "job_code": null,
        "location": "P",
        "inactive": 1,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 0,
        "bonus_type": "",
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "0.00",
        "pld": "0.00",
        "anl": "0.00",
        "sick_bal": "127.33",
        "rollover": 0,
        "last_timesheet": null
    },
    {
        "id": 59,
        "name": "O'RANCE, MICHAEL",
        "phone": "0431817775",
        "dob": "1989-09-05",
        "job_code": "613",
        "location": "P",
        "inactive": 0,
        "anniversary_dt": null,
        "company": "M",
        "bonus": 200,
        "bonus_type": "F",
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "4.50",
        "pld": "4.00",
        "anl": "6.57",
        "sick_bal": "225.72",
        "rollover": 0,
        "last_timesheet": 9606
    },
    {
        "id": 60,
        "name": "PARATHYRAS, STEVEN",
        "phone": "0431734627",
        "dob": "1995-09-28",
        "job_code": "525",
        "location": "P",
        "inactive": 1,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 0,
        "bonus_type": null,
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "49.00",
        "pld": "189.00",
        "anl": "37.63",
        "sick_bal": "174.68",
        "rollover": 0,
        "last_timesheet": null
    },
    {
        "id": 61,
        "name": "PATTEN, CONOR",
        "phone": "0481174498",
        "dob": "2000-08-02",
        "job_code": "594",
        "location": "L",
        "inactive": 0,
        "anniversary_dt": "2018-02-28",
        "company": "C",
        "bonus": 0,
        "bonus_type": null,
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "14.00",
        "pld": "2.00",
        "anl": "22.31",
        "sick_bal": "23.72",
        "rollover": 0,
        "last_timesheet": 9626
    },
    {
        "id": 62,
        "name": "Petralia , Daniel",
        "phone": "0402832230",
        "dob": "1997-11-07",
        "job_code": "604",
        "location": "P",
        "inactive": 0,
        "anniversary_dt": null,
        "company": "M",
        "bonus": 0,
        "bonus_type": null,
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "20.00",
        "pld": "15.25",
        "anl": "123.71",
        "sick_bal": "126.39",
        "rollover": 0,
        "last_timesheet": 9595
    },
    {
        "id": 64,
        "name": "PSAROUDIS, GABRIEL",
        "phone": "0414464474",
        "dob": "2001-01-13",
        "job_code": "594",
        "location": "A",
        "inactive": 1,
        "anniversary_dt": "2019-01-22",
        "company": "M",
        "bonus": 0,
        "bonus_type": null,
        "car_allowance": 0,
        "apprentice_year": "3",
        "rdo_bal": "46.75",
        "pld": "72.00",
        "anl": "74.12",
        "sick_bal": "49.32",
        "rollover": 0,
        "last_timesheet": null
    },
    {
        "id": 65,
        "name": "QUINN, RYAN",
        "phone": "0450115200",
        "dob": "1981-06-10",
        "job_code": "372",
        "location": "P",
        "inactive": 1,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 100,
        "bonus_type": "L",
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "24.00",
        "pld": "8.00",
        "anl": "85.09",
        "sick_bal": "141.48",
        "rollover": 0,
        "last_timesheet": null
    },
    {
        "id": 66,
        "name": "RICHES, WAYNE",
        "phone": "0414387578",
        "dob": "1977-01-07",
        "job_code": "579",
        "location": "P",
        "inactive": 1,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 0,
        "bonus_type": null,
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "2.00",
        "pld": "2.00",
        "anl": "22.24",
        "sick_bal": "62.57",
        "rollover": 0,
        "last_timesheet": null
    },
    {
        "id": 67,
        "name": "ROBERTS, EARL",
        "phone": "0403713270",
        "dob": "1985-05-04",
        "job_code": "517",
        "location": "P",
        "inactive": 1,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 0,
        "bonus_type": "",
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "1.00",
        "pld": "8.00",
        "anl": "19.62",
        "sick_bal": "206.49",
        "rollover": 0,
        "last_timesheet": null
    },
    {
        "id": 68,
        "name": "RODERICK, MATTHEW",
        "phone": "0481384854",
        "dob": "1958-08-05",
        "job_code": null,
        "location": "P",
        "inactive": 1,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 200,
        "bonus_type": "F",
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "10.00",
        "pld": "10.00",
        "anl": "19.05",
        "sick_bal": "0.00",
        "rollover": 0,
        "last_timesheet": null
    },
    {
        "id": 69,
        "name": "Ross De Moura, Rafael Luiz",
        "phone": "0404770344",
        "dob": "1987-10-29",
        "job_code": "001",
        "location": "O",
        "inactive": 0,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 0,
        "bonus_type": null,
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "0.00",
        "pld": "12.00",
        "anl": "9.58",
        "sick_bal": "61.52",
        "rollover": 0,
        "last_timesheet": 9599
    },
    {
        "id": 70,
        "name": "ROTH, DAVID",
        "phone": "0432422657",
        "dob": "1977-10-29",
        "job_code": "372",
        "location": "P",
        "inactive": 1,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 0,
        "bonus_type": "",
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "14.00",
        "pld": "37.00",
        "anl": "128.01",
        "sick_bal": "139.03",
        "rollover": 0,
        "last_timesheet": null
    },
    {
        "id": 71,
        "name": "SCOTT, EDWARD",
        "phone": "0432635200",
        "dob": "1981-01-31",
        "job_code": "604",
        "location": "P",
        "inactive": 0,
        "anniversary_dt": null,
        "company": "M",
        "bonus": 200,
        "bonus_type": "F",
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "11.00",
        "pld": "14.00",
        "anl": "9.53",
        "sick_bal": "385.40",
        "rollover": 0,
        "last_timesheet": 9596
    },
    {
        "id": 72,
        "name": "SILVA GAVIOLI, GUSTAVO",
        "phone": "0402768792",
        "dob": "1993-12-27",
        "job_code": "001",
        "location": "L",
        "inactive": 0,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 0,
        "bonus_type": null,
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "0.00",
        "pld": "0.00",
        "anl": "0.00",
        "sick_bal": "0.00",
        "rollover": 0,
        "last_timesheet": 9597
    },
    {
        "id": 73,
        "name": "STRINGER, JACKSON",
        "phone": "0420309065",
        "dob": "1986-08-11",
        "job_code": "594",
        "location": "P",
        "inactive": 0,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 0,
        "bonus_type": null,
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "6.00",
        "pld": "8.00",
        "anl": "22.62",
        "sick_bal": "12.30",
        "rollover": 0,
        "last_timesheet": 9616
    },
    {
        "id": 74,
        "name": "SUMMERS, ANDREW",
        "phone": "0422066168",
        "dob": "1988-03-04",
        "job_code": "579",
        "location": "A",
        "inactive": 0,
        "anniversary_dt": "2018-07-02",
        "company": "C",
        "bonus": 0,
        "bonus_type": null,
        "car_allowance": 0,
        "apprentice_year": "3",
        "rdo_bal": "18.00",
        "pld": "31.00",
        "anl": "9.86",
        "sick_bal": "112.86",
        "rollover": 0,
        "last_timesheet": 9580
    },
    {
        "id": 75,
        "name": "TAYLOR, SHANE",
        "phone": "0404379042",
        "dob": "1976-07-18",
        "job_code": "551",
        "location": "P",
        "inactive": 0,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 0,
        "bonus_type": "",
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "177.00",
        "pld": "1.50",
        "anl": "321.96",
        "sick_bal": "-14.24",
        "rollover": 0,
        "last_timesheet": null
    },
    {
        "id": 76,
        "name": "TINDALL, BRENDAN",
        "phone": "0450909720",
        "dob": "1987-09-09",
        "job_code": null,
        "location": "P",
        "inactive": 1,
        "anniversary_dt": null,
        "company": "M",
        "bonus": 0,
        "bonus_type": "",
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "10.00",
        "pld": "10.00",
        "anl": "77.54",
        "sick_bal": "0.00",
        "rollover": 0,
        "last_timesheet": null
    },
    {
        "id": 77,
        "name": "TORTORICI, JOSEPH",
        "phone": "0438478555",
        "dob": "1994-08-10",
        "job_code": "594",
        "location": "P",
        "inactive": 0,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 0,
        "bonus_type": "",
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "74.00",
        "pld": "192.75",
        "anl": "53.70",
        "sick_bal": "385.21",
        "rollover": 0,
        "last_timesheet": 9633
    },
    {
        "id": 78,
        "name": "TRIANTAFYLLIS, PETER",
        "phone": "0424379751",
        "dob": "1998-06-15",
        "job_code": "609",
        "location": "A",
        "inactive": 0,
        "anniversary_dt": "2018-12-30",
        "company": "C",
        "bonus": 0,
        "bonus_type": null,
        "car_allowance": 0,
        "apprentice_year": "4",
        "rdo_bal": "55.00",
        "pld": "45.00",
        "anl": "115.11",
        "sick_bal": "138.71",
        "rollover": 0,
        "last_timesheet": 9601
    },
    {
        "id": 79,
        "name": "TSALIAGOS, BILL",
        "phone": "0403189480",
        "dob": "1978-05-03",
        "job_code": "611",
        "location": "P",
        "inactive": 0,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 250,
        "bonus_type": "F",
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "18.00",
        "pld": "21.50",
        "anl": "121.72",
        "sick_bal": "404.30",
        "rollover": 0,
        "last_timesheet": 9585
    },
    {
        "id": 80,
        "name": "TSEKENIS, ATHAN",
        "phone": "0479090187",
        "dob": "1999-05-23",
        "job_code": "anl",
        "location": "A",
        "inactive": 0,
        "anniversary_dt": "2018-09-17",
        "company": "M",
        "bonus": 0,
        "bonus_type": "",
        "car_allowance": 0,
        "apprentice_year": "3",
        "rdo_bal": "78.00",
        "pld": "154.00",
        "anl": "5.40",
        "sick_bal": "153.05",
        "rollover": 0,
        "last_timesheet": 9636
    },
    {
        "id": 82,
        "name": "VAN DEN BOOGAARD, ROSS",
        "phone": null,
        "dob": "1979-03-03",
        "job_code": "604",
        "location": "P",
        "inactive": 0,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 100,
        "bonus_type": "L",
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "17.00",
        "pld": "8.00",
        "anl": "98.53",
        "sick_bal": "345.95",
        "rollover": 0,
        "last_timesheet": 9587
    },
    {
        "id": 83,
        "name": "WENIGER, RHODERIC",
        "phone": null,
        "dob": "1971-07-10",
        "job_code": "594",
        "location": "P",
        "inactive": 0,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 0,
        "bonus_type": "",
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "14.00",
        "pld": "16.00",
        "anl": "26.12",
        "sick_bal": "169.53",
        "rollover": 0,
        "last_timesheet": 9634
    },
    {
        "id": 84,
        "name": "YOUNG, PAUL",
        "phone": "0424237642",
        "dob": "1962-08-20",
        "job_code": null,
        "location": "P",
        "inactive": 1,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 0,
        "bonus_type": "",
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "2.00",
        "pld": "8.00",
        "anl": "20.16",
        "sick_bal": "0.00",
        "rollover": 0,
        "last_timesheet": null
    },
    {
        "id": 85,
        "name": "GHAMRAWI, MOHAMED",
        "phone": "0415082113",
        "dob": "1990-12-18",
        "job_code": "603",
        "location": "P",
        "inactive": 1,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 0,
        "bonus_type": null,
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "4.00",
        "pld": "4.00",
        "anl": "50.71",
        "sick_bal": "103.82",
        "rollover": 0,
        "last_timesheet": null
    },
    {
        "id": 86,
        "name": "VALLETTA, ADRIAN",
        "phone": "0404806481",
        "dob": "1989-12-13",
        "job_code": "604",
        "location": "P",
        "inactive": 0,
        "anniversary_dt": null,
        "company": "M",
        "bonus": 0,
        "bonus_type": "",
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "10.50",
        "pld": "44.00",
        "anl": "34.79",
        "sick_bal": "279.28",
        "rollover": 0,
        "last_timesheet": 9604
    },
    {
        "id": 87,
        "name": "WRIGLEY, MICHAEL",
        "phone": null,
        "dob": "1958-03-02",
        "job_code": "sick",
        "location": "P",
        "inactive": 1,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 0,
        "bonus_type": null,
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "2.00",
        "pld": "2.00",
        "anl": "0.58",
        "sick_bal": "0.24",
        "rollover": 0,
        "last_timesheet": null
    },
    {
        "id": 88,
        "name": "TSOHALIS, HARRY",
        "phone": "0406553004",
        "dob": "1976-12-04",
        "job_code": "099",
        "location": "P",
        "inactive": 0,
        "anniversary_dt": null,
        "company": "M",
        "bonus": 200,
        "bonus_type": "F",
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "4.25",
        "pld": "4.25",
        "anl": "2.75",
        "sick_bal": "427.13",
        "rollover": 0,
        "last_timesheet": 9593
    },
    {
        "id": 89,
        "name": "COONEY, NICHOLAS",
        "phone": "0433832314",
        "dob": "1986-08-07",
        "job_code": "001",
        "location": "P",
        "inactive": 1,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 200,
        "bonus_type": "F",
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "4.00",
        "pld": "10.50",
        "anl": "13.37",
        "sick_bal": "56.26",
        "rollover": 0,
        "last_timesheet": null
    },
    {
        "id": 90,
        "name": "JOHNSON, NATHAN",
        "phone": null,
        "dob": "2002-03-24",
        "job_code": "579",
        "location": "A",
        "inactive": 0,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 0,
        "bonus_type": null,
        "car_allowance": 0,
        "apprentice_year": "2",
        "rdo_bal": "86.00",
        "pld": "62.00",
        "anl": "64.62",
        "sick_bal": "80.28",
        "rollover": 0,
        "last_timesheet": 9582
    },
    {
        "id": 91,
        "name": "DE BIANCHI, CAMILA",
        "phone": "0416216748",
        "dob": "1993-12-04",
        "job_code": null,
        "location": "L",
        "inactive": 1,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 0,
        "bonus_type": "",
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "0.00",
        "pld": "0.00",
        "anl": "0.00",
        "sick_bal": "0.00",
        "rollover": 0,
        "last_timesheet": null
    },
    {
        "id": 92,
        "name": "GILL, SATWINDER",
        "phone": null,
        "dob": "1993-08-20",
        "job_code": "525",
        "location": "P",
        "inactive": 1,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 0,
        "bonus_type": null,
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "2.00",
        "pld": "4.00",
        "anl": "9.85",
        "sick_bal": "16.91",
        "rollover": 0,
        "last_timesheet": null
    },
    {
        "id": 93,
        "name": "Vincent, Jayden",
        "phone": null,
        "dob": "1995-12-06",
        "job_code": "594",
        "location": "P",
        "inactive": 0,
        "anniversary_dt": "2018-04-05",
        "company": "C",
        "bonus": 0,
        "bonus_type": null,
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "90.00",
        "pld": "67.75",
        "anl": "104.32",
        "sick_bal": "153.08",
        "rollover": 0,
        "last_timesheet": 9632
    },
    {
        "id": 94,
        "name": "AVTAROVSKI, DANNI",
        "phone": null,
        "dob": "1987-07-06",
        "job_code": "525",
        "location": "A",
        "inactive": 1,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 0,
        "bonus_type": null,
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "42.00",
        "pld": "18.25",
        "anl": "50.83",
        "sick_bal": "49.40",
        "rollover": 0,
        "last_timesheet": null
    },
    {
        "id": 95,
        "name": "TSEKENIS, DAMIAN",
        "phone": null,
        "dob": "2001-04-16",
        "job_code": "anl",
        "location": "A",
        "inactive": 1,
        "anniversary_dt": "2019-01-08",
        "company": "M",
        "bonus": 0,
        "bonus_type": null,
        "car_allowance": 0,
        "apprentice_year": "3",
        "rdo_bal": "62.25",
        "pld": "38.00",
        "anl": "137.86",
        "sick_bal": "172.86",
        "rollover": 0,
        "last_timesheet": null
    },
    {
        "id": 96,
        "name": "JOVICIC, STANKO",
        "phone": "0420802417",
        "dob": "1996-11-07",
        "job_code": "anl",
        "location": "P",
        "inactive": 1,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 0,
        "bonus_type": null,
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "14.00",
        "pld": "53.50",
        "anl": "78.81",
        "sick_bal": "50.47",
        "rollover": 0,
        "last_timesheet": null
    },
    {
        "id": 98,
        "name": "JENNINGS, DALLAS",
        "phone": "0420 247 796",
        "dob": "1998-08-06",
        "job_code": null,
        "location": "A",
        "inactive": 1,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 0,
        "bonus_type": "",
        "car_allowance": 0,
        "apprentice_year": "3",
        "rdo_bal": "4.00",
        "pld": "16.00",
        "anl": "14.42",
        "sick_bal": "16.92",
        "rollover": 0,
        "last_timesheet": null
    },
    {
        "id": 99,
        "name": "TRAN, BRANDON",
        "phone": "0420487166",
        "dob": "1996-09-12",
        "job_code": "608",
        "location": "A",
        "inactive": 0,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 0,
        "bonus_type": null,
        "car_allowance": 0,
        "apprentice_year": "2",
        "rdo_bal": "32.00",
        "pld": "24.00",
        "anl": "126.16",
        "sick_bal": "119.03",
        "rollover": 0,
        "last_timesheet": 9646
    },
    {
        "id": 100,
        "name": "OLIVEIRA MENDES, HALYSSON",
        "phone": null,
        "dob": "1989-08-18",
        "job_code": "594",
        "location": "L",
        "inactive": 0,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 0,
        "bonus_type": null,
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "0.00",
        "pld": "0.00",
        "anl": "0.00",
        "sick_bal": "0.00",
        "rollover": 0,
        "last_timesheet": 9624
    },
    {
        "id": 101,
        "name": "SANHUEZA, JORDAN",
        "phone": null,
        "dob": "1993-06-28",
        "job_code": null,
        "location": "A",
        "inactive": 1,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 0,
        "bonus_type": "",
        "car_allowance": 0,
        "apprentice_year": "3",
        "rdo_bal": "0.00",
        "pld": "0.00",
        "anl": "0.00",
        "sick_bal": "0.00",
        "rollover": 0,
        "last_timesheet": null
    },
    {
        "id": 102,
        "name": "AMBROSIUS, RYAN",
        "phone": "0470223650",
        "dob": "2018-06-04",
        "job_code": "pld",
        "location": "A",
        "inactive": 1,
        "anniversary_dt": "2019-01-12",
        "company": "C",
        "bonus": 0,
        "bonus_type": "",
        "car_allowance": 0,
        "apprentice_year": "4",
        "rdo_bal": "2.00",
        "pld": "6.00",
        "anl": "4.30",
        "sick_bal": "1.54",
        "rollover": 0,
        "last_timesheet": null
    },
    {
        "id": 103,
        "name": "PLATI, ROBERT",
        "phone": null,
        "dob": "1980-05-27",
        "job_code": "594",
        "location": "P",
        "inactive": 0,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 0,
        "bonus_type": "",
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "20.75",
        "pld": "80.75",
        "anl": "153.26",
        "sick_bal": "449.03",
        "rollover": 0,
        "last_timesheet": 9583
    },
    {
        "id": 104,
        "name": "Hackett, Luke",
        "phone": null,
        "dob": "1982-05-13",
        "job_code": "594",
        "location": "P",
        "inactive": 0,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 100,
        "bonus_type": "L",
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "24.00",
        "pld": "32.00",
        "anl": "87.85",
        "sick_bal": "106.13",
        "rollover": 0,
        "last_timesheet": 9622
    },
    {
        "id": 105,
        "name": "TAYLOR, JOSHUA",
        "phone": "0410131195",
        "dob": "2000-02-12",
        "job_code": "anl",
        "location": "A",
        "inactive": 1,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 0,
        "bonus_type": null,
        "car_allowance": 0,
        "apprentice_year": "1",
        "rdo_bal": "0.00",
        "pld": "0.00",
        "anl": "0.00",
        "sick_bal": "0.00",
        "rollover": 0,
        "last_timesheet": null
    },
    {
        "id": 106,
        "name": "TIMBERY, ISAAC",
        "phone": "0416544348",
        "dob": "1994-11-01",
        "job_code": "525",
        "location": "A",
        "inactive": 1,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 0,
        "bonus_type": null,
        "car_allowance": 0,
        "apprentice_year": "3",
        "rdo_bal": "0.00",
        "pld": "0.00",
        "anl": "0.00",
        "sick_bal": "0.00",
        "rollover": 0,
        "last_timesheet": null
    },
    {
        "id": 107,
        "name": "Lamim Kobayashi, Caio",
        "phone": "0415186325",
        "dob": "1990-10-24",
        "job_code": "001",
        "location": "O",
        "inactive": 0,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 0,
        "bonus_type": null,
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "0.00",
        "pld": "0.00",
        "anl": "0.00",
        "sick_bal": "0.00",
        "rollover": 0,
        "last_timesheet": null
    },
    {
        "id": 124,
        "name": "ACHELLES, CHRISTOPHER",
        "phone": "0498344494",
        "dob": "1990-09-22",
        "job_code": "551",
        "location": "P",
        "inactive": 1,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 100,
        "bonus_type": "L",
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "13.00",
        "pld": "8.00",
        "anl": "14.46",
        "sick_bal": "26.20",
        "rollover": 0,
        "last_timesheet": null
    },
    {
        "id": 108,
        "name": "DA SILVA, OZEIAS ANTONIO",
        "phone": null,
        "dob": "1989-09-01",
        "job_code": "551",
        "location": "L",
        "inactive": 1,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 0,
        "bonus_type": null,
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "0.00",
        "pld": "0.00",
        "anl": "0.00",
        "sick_bal": "0.00",
        "rollover": 0,
        "last_timesheet": null
    },
    {
        "id": 109,
        "name": "Allan, Paul",
        "phone": "0412874311",
        "dob": "1991-12-14",
        "job_code": "594",
        "location": "P",
        "inactive": 0,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 0,
        "bonus_type": null,
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "10.00",
        "pld": "19.00",
        "anl": "41.04",
        "sick_bal": "43.99",
        "rollover": 0,
        "last_timesheet": 9620
    },
    {
        "id": 110,
        "name": "BERMUDEZ, ROYERS",
        "phone": "0414344046",
        "dob": "1992-05-23",
        "job_code": "604",
        "location": "L",
        "inactive": 0,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 0,
        "bonus_type": null,
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "0.00",
        "pld": "0.00",
        "anl": "0.00",
        "sick_bal": "0.00",
        "rollover": 0,
        "last_timesheet": 9605
    },
    {
        "id": 111,
        "name": "PHIPPS, TYSON",
        "phone": "0432240084",
        "dob": "2000-05-14",
        "job_code": "525",
        "location": "A",
        "inactive": 1,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 0,
        "bonus_type": null,
        "car_allowance": 0,
        "apprentice_year": "2",
        "rdo_bal": "0.00",
        "pld": "0.00",
        "anl": "1.16",
        "sick_bal": "0.60",
        "rollover": 0,
        "last_timesheet": null
    },
    {
        "id": 112,
        "name": "Farah, Paul",
        "phone": "0435746492",
        "dob": "1992-03-23",
        "job_code": "609",
        "location": "P",
        "inactive": 1,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 0,
        "bonus_type": null,
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "10.00",
        "pld": "8.00",
        "anl": "27.54",
        "sick_bal": "46.75",
        "rollover": 0,
        "last_timesheet": null
    },
    {
        "id": 113,
        "name": "BARDJIKJ, BOJAN",
        "phone": "0449638238",
        "dob": "1985-04-26",
        "job_code": "604",
        "location": "P",
        "inactive": 0,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 0,
        "bonus_type": "",
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "50.00",
        "pld": "46.00",
        "anl": "58.47",
        "sick_bal": "129.19",
        "rollover": 0,
        "last_timesheet": 9589
    },
    {
        "id": 114,
        "name": "ELGHOUL, OMAR",
        "phone": "0404403300",
        "dob": "1994-07-12",
        "job_code": "pld",
        "location": "P",
        "inactive": 1,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 0,
        "bonus_type": null,
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "8.00",
        "pld": "24.00",
        "anl": "40.39",
        "sick_bal": "19.67",
        "rollover": 0,
        "last_timesheet": null
    },
    {
        "id": 115,
        "name": "POULOS, ANDREAS",
        "phone": "0411329809",
        "dob": "1995-04-20",
        "job_code": "604",
        "location": "P",
        "inactive": 0,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 0,
        "bonus_type": "",
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "92.00",
        "pld": "32.00",
        "anl": "74.47",
        "sick_bal": "89.19",
        "rollover": 0,
        "last_timesheet": 9592
    },
    {
        "id": 116,
        "name": "KOULOURIS, JAMES",
        "phone": null,
        "dob": "1978-03-16",
        "job_code": "551",
        "location": "P",
        "inactive": 1,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 0,
        "bonus_type": null,
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "0.00",
        "pld": "0.00",
        "anl": "0.00",
        "sick_bal": "0.00",
        "rollover": 0,
        "last_timesheet": null
    },
    {
        "id": 117,
        "name": "TURNER, OWEN",
        "phone": null,
        "dob": "1996-11-21",
        "job_code": "525",
        "location": "A",
        "inactive": 1,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 0,
        "bonus_type": "",
        "car_allowance": 0,
        "apprentice_year": "4",
        "rdo_bal": "6.00",
        "pld": "2.25",
        "anl": "33.92",
        "sick_bal": "6.15",
        "rollover": 0,
        "last_timesheet": null
    },
    {
        "id": 118,
        "name": "Astudillo, Gonzalo",
        "phone": "0423501935",
        "dob": "1979-01-21",
        "job_code": "525",
        "location": "P",
        "inactive": 1,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 0,
        "bonus_type": null,
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "0.00",
        "pld": "0.00",
        "anl": "0.00",
        "sick_bal": "0.00",
        "rollover": 0,
        "last_timesheet": null
    },
    {
        "id": 119,
        "name": "BAZOUNI, ROUMANOS",
        "phone": "0426252407",
        "dob": "1993-09-04",
        "job_code": "582",
        "location": "A",
        "inactive": 0,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 0,
        "bonus_type": null,
        "car_allowance": 0,
        "apprentice_year": "4",
        "rdo_bal": "4.00",
        "pld": "12.25",
        "anl": "11.59",
        "sick_bal": "77.79",
        "rollover": 0,
        "last_timesheet": 9649
    },
    {
        "id": 120,
        "name": "RICHARDSON, JAY",
        "phone": "0404313807",
        "dob": "1977-10-31",
        "job_code": "594",
        "location": "P",
        "inactive": 1,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 0,
        "bonus_type": null,
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "14.00",
        "pld": "53.50",
        "anl": "34.47",
        "sick_bal": "43.98",
        "rollover": 0,
        "last_timesheet": null
    },
    {
        "id": 121,
        "name": "SAYLES, GARETH",
        "phone": "0438473517",
        "dob": "1984-12-14",
        "job_code": "582",
        "location": "P",
        "inactive": 1,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 0,
        "bonus_type": null,
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "42.00",
        "pld": "41.25",
        "anl": "79.43",
        "sick_bal": "55.69",
        "rollover": 0,
        "last_timesheet": null
    },
    {
        "id": 123,
        "name": "RODRIGUEZ, JESUS ALBERTO ANGELINO",
        "phone": "0402197613",
        "dob": "1989-05-15",
        "job_code": "551",
        "location": "L",
        "inactive": 1,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 0,
        "bonus_type": null,
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "0.00",
        "pld": "0.00",
        "anl": "0.00",
        "sick_bal": "0.00",
        "rollover": 0,
        "last_timesheet": null
    },
    {
        "id": 125,
        "name": "INGLETON, MATTHEW",
        "phone": "0450299765",
        "dob": "1996-06-25",
        "job_code": "594",
        "location": "P",
        "inactive": 0,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 0,
        "bonus_type": "",
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "36.00",
        "pld": "46.00",
        "anl": "36.93",
        "sick_bal": "78.43",
        "rollover": 0,
        "last_timesheet": 9619
    },
    {
        "id": 126,
        "name": "Kasikieris, Dimitri",
        "phone": "0423293509",
        "dob": "1989-03-21",
        "job_code": "551",
        "location": "P",
        "inactive": 1,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 0,
        "bonus_type": null,
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "0.00",
        "pld": "0.00",
        "anl": "0.00",
        "sick_bal": "0.00",
        "rollover": 0,
        "last_timesheet": null
    },
    {
        "id": 127,
        "name": "Allan, Jamie",
        "phone": "0413233372",
        "dob": "1997-04-13",
        "job_code": "582",
        "location": "P",
        "inactive": 1,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 0,
        "bonus_type": null,
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "4.00",
        "pld": "54.00",
        "anl": "62.16",
        "sick_bal": "7.06",
        "rollover": 0,
        "last_timesheet": null
    },
    {
        "id": 128,
        "name": "FORD, JOHNATHON",
        "phone": "0426262246",
        "dob": "1994-04-12",
        "job_code": "608",
        "location": "P",
        "inactive": 1,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 0,
        "bonus_type": null,
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "12.00",
        "pld": "8.00",
        "anl": "78.16",
        "sick_bal": "39.06",
        "rollover": 0,
        "last_timesheet": null
    },
    {
        "id": 129,
        "name": "Panayi, Nicholas",
        "phone": "0410788041",
        "dob": "1988-02-27",
        "job_code": "500",
        "location": "P",
        "inactive": 1,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 0,
        "bonus_type": null,
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "18.00",
        "pld": "17.75",
        "anl": "59.09",
        "sick_bal": "44.53",
        "rollover": 0,
        "last_timesheet": null
    },
    {
        "id": 130,
        "name": "De Matos Vilela, Silas",
        "phone": "0424202570",
        "dob": "1990-07-25",
        "job_code": "551",
        "location": "L",
        "inactive": 1,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 0,
        "bonus_type": null,
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "0.00",
        "pld": "0.00",
        "anl": "0.00",
        "sick_bal": "0.00",
        "rollover": 0,
        "last_timesheet": null
    },
    {
        "id": 131,
        "name": "KAMOUN, TAHA",
        "phone": "0423344153",
        "dob": "1985-10-21",
        "job_code": "525",
        "location": "P",
        "inactive": 1,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 0,
        "bonus_type": null,
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "4.00",
        "pld": "6.00",
        "anl": "21.89",
        "sick_bal": "30.77",
        "rollover": 0,
        "last_timesheet": null
    },
    {
        "id": 133,
        "name": "ANDRONICUS, JARED",
        "phone": "0447011266",
        "dob": "1998-09-03",
        "job_code": "551",
        "location": "A",
        "inactive": 1,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 0,
        "bonus_type": null,
        "car_allowance": 0,
        "apprentice_year": "2",
        "rdo_bal": "0.00",
        "pld": "0.00",
        "anl": "0.00",
        "sick_bal": "0.00",
        "rollover": 0,
        "last_timesheet": null
    },
    {
        "id": 134,
        "name": "Medina, Jose",
        "phone": "0449548449",
        "dob": "1984-11-01",
        "job_code": "551",
        "location": "L",
        "inactive": 1,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 0,
        "bonus_type": null,
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "0.00",
        "pld": "0.00",
        "anl": "0.00",
        "sick_bal": "0.00",
        "rollover": 0,
        "last_timesheet": null
    },
    {
        "id": 135,
        "name": "SALAS ANGELLOTTI, CAROLINA",
        "phone": "0415258022",
        "dob": "1989-07-21",
        "job_code": "551",
        "location": "L",
        "inactive": 1,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 0,
        "bonus_type": null,
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "0.00",
        "pld": "0.00",
        "anl": "0.00",
        "sick_bal": "0.00",
        "rollover": 0,
        "last_timesheet": null
    },
    {
        "id": 136,
        "name": "WRIGLEY, TIM",
        "phone": null,
        "dob": "1989-07-24",
        "job_code": "001",
        "location": "P",
        "inactive": 1,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 0,
        "bonus_type": null,
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "38.00",
        "pld": "42.00",
        "anl": "12.93",
        "sick_bal": "46.45",
        "rollover": 0,
        "last_timesheet": null
    },
    {
        "id": 138,
        "name": "Hassanpour, Allan",
        "phone": "0435717688",
        "dob": "2001-03-13",
        "job_code": "582",
        "location": "A",
        "inactive": 1,
        "anniversary_dt": "2018-01-01",
        "company": "C",
        "bonus": 0,
        "bonus_type": null,
        "car_allowance": 0,
        "apprentice_year": "1",
        "rdo_bal": "6.00",
        "pld": "36.00",
        "anl": "38.31",
        "sick_bal": "47.68",
        "rollover": 0,
        "last_timesheet": null
    },
    {
        "id": 137,
        "name": "Jarrett, Matthew",
        "phone": "0400204642",
        "dob": "1979-12-31",
        "job_code": "579",
        "location": "P",
        "inactive": 0,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 100,
        "bonus_type": "L",
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "10.00",
        "pld": "18.00",
        "anl": "23.78",
        "sick_bal": "98.73",
        "rollover": 0,
        "last_timesheet": 9584
    },
    {
        "id": 140,
        "name": "WISEMAN, DANIEL",
        "phone": "0402549466",
        "dob": "1989-12-08",
        "job_code": "608",
        "location": "P",
        "inactive": 0,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 0,
        "bonus_type": "",
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "44.00",
        "pld": "72.00",
        "anl": "64.94",
        "sick_bal": "45.93",
        "rollover": 0,
        "last_timesheet": 9642
    },
    {
        "id": 141,
        "name": "AMRIE, AHMED",
        "phone": "0404634626",
        "dob": "1992-03-15",
        "job_code": "594",
        "location": "A",
        "inactive": 0,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 0,
        "bonus_type": "",
        "car_allowance": 0,
        "apprentice_year": "2",
        "rdo_bal": "26.00",
        "pld": "44.00",
        "anl": "117.54",
        "sick_bal": "27.74",
        "rollover": 0,
        "last_timesheet": 9612
    },
    {
        "id": 142,
        "name": "SLOGGETT, DANIEL",
        "phone": "0423695659",
        "dob": "1988-09-10",
        "job_code": "551",
        "location": "P",
        "inactive": 1,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 0,
        "bonus_type": null,
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "8.00",
        "pld": "6.00",
        "anl": "9.46",
        "sick_bal": "21.22",
        "rollover": 0,
        "last_timesheet": null
    },
    {
        "id": 145,
        "name": "REDDEN, DYLAN",
        "phone": "0468366682",
        "dob": "2000-04-25",
        "job_code": "608",
        "location": "A",
        "inactive": 0,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 0,
        "bonus_type": null,
        "car_allowance": 0,
        "apprentice_year": "4",
        "rdo_bal": "27.25",
        "pld": "53.00",
        "anl": "48.62",
        "sick_bal": "67.09",
        "rollover": 0,
        "last_timesheet": 9645
    },
    {
        "id": 143,
        "name": "Pizanis, Leon",
        "phone": "0415 323 112",
        "dob": "1975-11-28",
        "job_code": "001",
        "location": "P",
        "inactive": 1,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 0,
        "bonus_type": null,
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "0.00",
        "pld": "0.00",
        "anl": "0.00",
        "sick_bal": "0.00",
        "rollover": 0,
        "last_timesheet": null
    },
    {
        "id": 144,
        "name": "ABARCA, SAMUEL",
        "phone": "0420517205",
        "dob": "1999-10-11",
        "job_code": "604",
        "location": "A",
        "inactive": 0,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 0,
        "bonus_type": null,
        "car_allowance": 0,
        "apprentice_year": "2",
        "rdo_bal": "58.00",
        "pld": "90.00",
        "anl": "41.08",
        "sick_bal": "2.51",
        "rollover": 0,
        "last_timesheet": 9586
    },
    {
        "id": 148,
        "name": "ATEVALY DANNY FONUA",
        "phone": null,
        "dob": "1978-01-22",
        "job_code": "594",
        "location": "L",
        "inactive": 1,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 0,
        "bonus_type": null,
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "0.00",
        "pld": "0.00",
        "anl": "0.00",
        "sick_bal": "0.00",
        "rollover": 0,
        "last_timesheet": null
    },
    {
        "id": 146,
        "name": "Morilla, Mary",
        "phone": "0425 152 369",
        "dob": "1979-10-08",
        "job_code": "001",
        "location": "O",
        "inactive": 1,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 0,
        "bonus_type": null,
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "0.00",
        "pld": "0.00",
        "anl": "0.00",
        "sick_bal": "0.00",
        "rollover": 0,
        "last_timesheet": null
    },
    {
        "id": 147,
        "name": "Busteed, Noah",
        "phone": null,
        "dob": "1998-11-16",
        "job_code": "594",
        "location": "A",
        "inactive": 0,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 0,
        "bonus_type": null,
        "car_allowance": 0,
        "apprentice_year": "1",
        "rdo_bal": "18.00",
        "pld": "54.00",
        "anl": "12.93",
        "sick_bal": "42.44",
        "rollover": 0,
        "last_timesheet": 9615
    },
    {
        "id": 149,
        "name": "SALETILI FIFITA",
        "phone": null,
        "dob": "1986-06-18",
        "job_code": "594",
        "location": "P",
        "inactive": 1,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 0,
        "bonus_type": null,
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "0.00",
        "pld": "0.00",
        "anl": "0.00",
        "sick_bal": "0.00",
        "rollover": 0,
        "last_timesheet": null
    },
    {
        "id": 150,
        "name": "FONUA, ATE VALU",
        "phone": "0449625659",
        "dob": "1978-01-22",
        "job_code": "594",
        "location": "L",
        "inactive": 0,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 0,
        "bonus_type": null,
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "16.00",
        "pld": "4.00",
        "anl": "34.31",
        "sick_bal": "20.15",
        "rollover": 0,
        "last_timesheet": 9621
    },
    {
        "id": 151,
        "name": "Knapton, Jai",
        "phone": null,
        "dob": "2001-05-21",
        "job_code": "608",
        "location": "A",
        "inactive": 0,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 0,
        "bonus_type": null,
        "car_allowance": 0,
        "apprentice_year": "1",
        "rdo_bal": "12.00",
        "pld": "12.00",
        "anl": "18.46",
        "sick_bal": "9.23",
        "rollover": 0,
        "last_timesheet": 9647
    },
    {
        "id": 152,
        "name": "Carruthers, Hayden",
        "phone": "0412 916 626",
        "dob": "1994-03-20",
        "job_code": null,
        "location": "P",
        "inactive": 0,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 0,
        "bonus_type": null,
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "6.00",
        "pld": "6.00",
        "anl": "9.23",
        "sick_bal": "4.61",
        "rollover": 0,
        "last_timesheet": 9617
    },
    {
        "id": 153,
        "name": "Roth, David",
        "phone": "0432422657",
        "dob": "1977-10-29",
        "job_code": null,
        "location": "P",
        "inactive": 0,
        "anniversary_dt": null,
        "company": "C",
        "bonus": 0,
        "bonus_type": null,
        "car_allowance": 0,
        "apprentice_year": null,
        "rdo_bal": "0.00",
        "pld": "0.00",
        "anl": "0.00",
        "sick_bal": "0.00",
        "rollover": 0,
        "last_timesheet": 9635
    },
    {
        "id": 154,
        "name": "Rafael Ross",
        "phone": null,
        "dob": null,
        "job_code": null,
        "location": "O",
        "inactive": 1,
        "anniversary_dt": null,
        "company": "C",
        "bonus": null,
        "bonus_type": null,
        "car_allowance": null,
        "apprentice_year": null,
        "rdo_bal": null,
        "pld": null,
        "anl": null,
        "sick_bal": "0.00",
        "rollover": 0,
        "last_timesheet": null
    },
    {
        "id": 155,
        "name": "Marli Ross",
        "phone": null,
        "dob": null,
        "job_code": null,
        "location": "O",
        "inactive": 1,
        "anniversary_dt": null,
        "company": "C",
        "bonus": null,
        "bonus_type": null,
        "car_allowance": null,
        "apprentice_year": null,
        "rdo_bal": null,
        "pld": null,
        "anl": null,
        "sick_bal": "0.00",
        "rollover": 0,
        "last_timesheet": null
    },
    {
        "id": 156,
        "name": "Luizao Trovao",
        "phone": null,
        "dob": null,
        "job_code": null,
        "location": null,
        "inactive": 0,
        "anniversary_dt": null,
        "company": "C",
        "bonus": null,
        "bonus_type": null,
        "car_allowance": null,
        "apprentice_year": null,
        "rdo_bal": null,
        "pld": null,
        "anl": null,
        "sick_bal": "0.00",
        "rollover": 0,
        "last_timesheet": null
    }
]

console.log(employees)

let dateTime = new Date();


const tableSize = {
    name: 0.5,
    dob: 0.3,
    phone: 0.3,
    job: 0.3,
    apprentice_year: 0.3,
    anniversary_dt: 0.3
}

// Create Document Component
const MyDocument = () => (
    <Document>
        <Page size="A4" style={styles.page} debug={debug}>
            <View>
                <Text style={{ textAlign: 'right', fontStyle: 'italic', fontSize: 10 }} fixed>Printed: {dateTime.toLocaleDateString()}</Text>
                <Image style={{ position: 'absolute', right: 0, top: 5, width: '100px' }} src="/img/logo.jpg" />
                <View style={{ flex: 1 }}>
                    <Text style={{ textAlign: 'center', fontStyle: 'italic', fontSize: 15 }}>LIST OF EMPLOYEES</Text>
                    
                </View>

                <View style={styles.table.tableView}>
                <Table
                    data={employees}
                >
                    <TableHeader style={styles.table.tableHead}>
                        <TableCell weighting={tableSize.name} textAlign="center" style={{fontSize: '10pt'}}>Name</TableCell>
                        <TableCell weighting={tableSize.dob} textAlign="center">D.O.B</TableCell>
                        <TableCell weighting={tableSize.phone} textAlign="center">Phone</TableCell>
                        <TableCell weighting={tableSize.role} textAlign="center">Role</TableCell>
                        <TableCell weighting={tableSize.job} textAlign="center">Job</TableCell>
                        <TableCell weighting={tableSize.apprentice_year} textAlign="center">Apprentice Year</TableCell>
                        <TableCell weighting={tableSize.anniversary_dt} textAlign="center">Apprentice Rollover</TableCell>
                    </TableHeader>
                    <TableBody>
                        <DataTableCell getContent={(r) => r.name} weighting={tableSize.name}/>
                        <DataTableCell getContent={(r) => r.dob} weighting={tableSize.dob}/>
                        <DataTableCell getContent={(r) => r.phone} weighting={tableSize.phone}/>
                        <DataTableCell getContent={(r) => r.role} weighting={tableSize.role}/>
                        <DataTableCell getContent={(r) => r.job} weighting={tableSize.job}/>
                        <DataTableCell getContent={(r) => r.apprentice_year} weighting={tableSize.apprentice_year}/>
                        <DataTableCell getContent={(r) => r.anniversary_dt} weighting={tableSize.anniversary_dt}/>
                    </TableBody>
                </Table>

                </View>
            </View>
        </Page>
    </Document>
);


const ListEmployees = () => (
    <PDFViewer width={'100%'} height={900}>
        <MyDocument />
    </PDFViewer>
);



const ListEmployeesDownload = () => (
    <div>
        <PDFDownloadLink document={<MyDocument />} fileName="somename.pdf">
            {({ blob, url, loading, error }) => (loading ? 'Loading document...' : 'Download now!')}
        </PDFDownloadLink>
    </div>
)

export default ListEmployees;